env:
  global:
  - GIT_COMMITTER_NAME=y-kurami
  - GIT_COMMITTER_EMAIL=yosuke.kurami@gmail.com
  - GIT_AUTHOR_NAME=Quramy
  - GIT_AUTHOR_EMAIL=yosuke.kurami@gmail.com
language: node_js
node_js:
- 8
- 10
- 12
before_script:
- yarn install --frozen-lockfile
script:
- yarn test:ci
deploy:
  provider: npm
  email: yosuke.kurami@gmail.com
  api_key: $NPM_AUTH_TOKEN
  on:
    tags: true
    repo: Quramy/typed-css-modules
