env:
  global:
  - GIT_COMMITTER_NAME=y-kurami
  - GIT_COMMITTER_EMAIL=yosuke.kurami@gmail.com
  - GIT_AUTHOR_NAME=Quramy
  - GIT_AUTHOR_EMAIL=yosuke.kurami@gmail.com
language: node_js
node_js:
- 4.2.3
before_install:
- npm install -g gulp
- npm install
script:
- gulp test
deploy:
  provider: npm
  email: yosuke.kurami@gmail.com
  api_key:
    secure: hSYXqWPQ2P3aFrXnLl87Whi2atYVi4QL7VWCrQ2ZwY6Hn2kJJQyKQozMT0Xysw5ujriGLpe7l9uKgiZtVQa1iD3prpl+207pUT3q4bD2AKI6C6GQeA4+5cGIpt1syiJ91ipHnR7y8ANy2X4rle2j/o+jGKHXKWc5gJgvylPmoQC/5YkSKz+TcWQab++6dxZ5qvbpoinRU0gb8J0weuxscPCofYgG4d8VTTeio2hbHqw9WdfmMLv02AHHRDsAW4K1nneHdIgDVP4hv4K27wWcFyrFLEc2ci82BV0WNnyXwxuJ5Sj5x7HsFgrGSMfp5/HCIR3ptE92H5G7rlOWErTw/tLKvB4fxQiJ+YdP510yiivpXTbMI6tibvOHslP6zes46E9aC1ojooPa6RgKkosFRkjQgvNAqfY8DgvTK+npUDnwTeLZbdjuqicM5MZk3jnex+8cle+gWMkrOtnjij5U9Ghq0weJU9Izrs+NmZTm+rvZb84PrgeMkb8hyH5U3LJDpioIEgJx0lgi/Ia59Ls2QvX2+yFR0JsCxERHb0ZqA9CkAe1fpT6qxxYsuKmDtm2sR4cQGkWfK7/4ZcKKAaNuEB1esAja4uwyRRice1U7TiXUw/8GyBfHWZwofPjx3pq6AXl2eZ9/26ssvzwV75MtK0QDLc5MvRvMTbqSmWQAS8Q=
  on:
    tags: true
    repo: Quramy/typed-css-modules
