name: CI for Node.js

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - run: npm run lint

  test:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Node.js
          - node: '16.x'
          - node: '18.x'
          # less
          - node: '16.x'
            less: '^3.0.0'
          - node: '18.x'
            less: '^3.0.0'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
          cache: 'npm'
      - run: npm install

      - run: npm i -D less@${{ matrix.less }}
        if: ${{ matrix.less }}

      - run: npm run test
        env:
          CI: true

  verify-if-example-is-outdated:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      - run: npm install
      - run: npm run build
      - run: npm run hcm -w example -- --watch=false
      - name: Verify if there is a difference in packages/example
        run: |
          git add --intent-to-add .
          git diff --exit-code packages/example
